name: Setup CI
runs:
  using: composite
  steps:
    - name: Setup Node.js 22
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 22.1.0
        cache: "npm"
    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      name: Setup Java Step
      with:
        distribution: temurin
        java-version: 17.0.2
    - name: Setup Gradle Step
      uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3
      with:
        gradle-version: 8.7
