# https://github.com/actions/starter-workflows/blob/main/automation/greetings.yml
name: Greetings
on:
  - pull_request_target
  - issues
jobs:
  greeting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for opening this issue! 🎉"
          pr-message: "Thank you for opening this pull request! 🎉"
