# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
name: Release Workflow
on:
  push:
    branches:
      - main # or main
permissions:
  contents: read # for checkout
jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout Step
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js Step
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies Step
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies Step
        run: npm audit signatures
      - name: Release Step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
